from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import os
import numpy as np

app = Flask(__name__)
CORS(app)

# Load Models (We do this during startup)
MODEL_DIR = os.path.join(os.path.dirname(__file__), 'models')
stock_model = None
fraud_model = None

try:
    stock_model = joblib.load(os.path.join(MODEL_DIR, 'stock_prediction_model.pkl'))
    fraud_model = joblib.load(os.path.join(MODEL_DIR, 'fraud_detection_model.pkl'))
    print("Models loaded successfully.")
except Exception as e:
    print(f"Warning: Models not loaded. Please run train_models.py first. Error: {e}")

@app.route('/predict-stock', methods=['POST'])
def predict_stock():
    if not stock_model:
        return jsonify({"error": "Stock prediction model not loaded"}), 500
        
    data = request.json
    if not data or 'users' not in data:
        return jsonify({"error": "Missing 'users' field in request payload."}), 400
        
    users = data.get('users')
    
    # Linear Regression models output lists/arrays. We predict based on [users]
    X_input = np.array([[users]])
    rice_demand = stock_model['rice'].predict(X_input)[0]
    sugar_demand = stock_model['sugar'].predict(X_input)[0]
    wheat_demand = stock_model['wheat'].predict(X_input)[0]
    
    return jsonify({
        "predicted_rice_demand": round(float(rice_demand), 2),
        "predicted_sugar_demand": round(float(sugar_demand), 2),
        "predicted_wheat_demand": round(float(wheat_demand), 2)
    })

@app.route('/detect-fraud', methods=['POST'])
def detect_fraud():
    if not fraud_model:
        return jsonify({"error": "Fraud detection model not loaded"}), 500
        
    data = request.json
    if not data or 'user_requests' not in data or 'duplicate_attempt' not in data:
        return jsonify({"error": "Missing required fields 'user_requests' and 'duplicate_attempt'."}), 400
        
    user_requests = data.get('user_requests')
    duplicate_attempt = data.get('duplicate_attempt')
    
    X_input = np.array([[user_requests, duplicate_attempt]])
    prediction = fraud_model.predict(X_input)[0]
    
    return jsonify({
        "fraud_detected": bool(prediction)
    })

@app.route('/usage-pattern', methods=['GET'])
def usage_pattern():
    # K-Means clustering usually provides insight offline, but we simulate the clustered return here 
    # based on the standard domain logic generated by our offline model.
    return jsonify({
        "peak_time": "Morning (8AM - 12PM), Evening (5PM - 8PM)",
        "low_demand_time": "Afternoon (1PM - 4PM), Night (9PM - 7AM)",
        "insights": "Clusters indicate high congestion during early morning shifts."
    })

if __name__ == '__main__':
    print("🚀 Starting ML Service on port 6000...")
    app.run(host='0.0.0.0', port=6000, debug=True)
